### ISSUE TITLE
Releases v0.0.1

### ISSUE THREAD

**Issue by hchqin** [UBC-MDS/Student_Success_Predict_Group15#14]
Dears, 

We have reached milestone 1! Through our collaboration, we have finished setting up the project repo and building up our initial machine-learning model. 

Please check the v0.0.1 release to approve the release or to comment on any potential changes. 

Thanks,

**Comment by tangyl92** [comment]
Thank you team.

**Comment by billwan96** [comment]
Thanks all. Great work!!
